name: Bot Automático

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
      # …otros pasos…
